title:              Analysing College Scorecards to choose the best
email:              akhileshkeerthi@gmail.com
description:        College scorecards Project for the prospective students and staff
author:             Sai Kumar Ailli / Akhilesh
baseurl:            "/docs"
url:                "https://akhiltodecode.github.io/Keerthi_AIT580/"

# Social platforms
twitter_username:   coll
github_username:    coll1
facebook_username:  coll2
instagram_username:   coll3
linkedin_username:   coll4

#ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
